import { useMutation } from "@tanstack/react-query";
import {
  Sparkles,
  BrainCircuit,
  ArrowRight,
} from "lucide-react";
import { toast } from "sonner";

import { analyzePortfolio } from "../../services/ai.service";
import Card from "../ui/Card";
import Button from "../ui/Button";

export default function AIAnalysis() {
  const analysisMutation = useMutation({
    mutationFn: analyzePortfolio,

    onSuccess: () => {
      toast.success("AI analysis generated successfully!");
    },

    onError: () => {
      toast.error("Failed to generate AI analysis.");
    },
  });

  return (
    <Card>
      <div className="mb-8 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="rounded-xl bg-purple-600 p-3 text-white shadow-md">
            <BrainCircuit size={24} />
          </div>

          <div>
            <h2 className="text-2xl font-bold text-slate-900">
              AI Portfolio Analysis
            </h2>

            <p className="text-sm text-slate-500">
              Generate intelligent insights for your portfolio.
            </p>
          </div>
        </div>

        <Button
          onClick={() => analysisMutation.mutate()}
          disabled={analysisMutation.isPending}
          className="flex items-center gap-2"
        >
          <Sparkles size={18} />

          {analysisMutation.isPending
            ? "Analyzing..."
            : "Analyze Portfolio"}
        </Button>
      </div>

      {!analysisMutation.data && (
        <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-10 text-center">
          <BrainCircuit
            size={48}
            className="mx-auto mb-4 text-slate-400"
          />

          <h3 className="text-lg font-semibold text-slate-700">
            No AI Analysis Yet
          </h3>

          <p className="mt-2 text-slate-500">
            Click the button above to generate AI-powered
            investment insights.
          </p>
        </div>
      )}

      {analysisMutation.data && (
        <div className="rounded-2xl border border-purple-100 bg-gradient-to-br from-purple-50 to-white p-8 shadow-sm">
          <div className="mb-6 flex items-center gap-2 text-purple-700">
            <Sparkles size={22} />

            <h3 className="text-xl font-bold">
              AI Recommendations
            </h3>
          </div>

          <div className="whitespace-pre-wrap leading-8 text-slate-700">
            {analysisMutation.data.data.analysis}
          </div>

          <div className="mt-8 flex justify-end">
            <span className="flex items-center gap-2 font-semibold text-purple-600">
              Generated by AI

              <ArrowRight size={18} />
            </span>
          </div>
        </div>
      )}
    </Card>
  );
}